# Generated by Django 4.2.6 on 2023-11-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_alter_cruise_destinations_alter_destination_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(),
        ),
    ]
