# Generated by Django 4.2.7 on 2023-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_alter_destination_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='destinations', to='relecloud.destination'),
        ),
    ]
